name: Release to npm

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: npm install and build
      run: |
        npm i
        npm run build

  release:
    on:
      branches: 
        - main
      needs: build
      runs-on: ubuntu-latest
      if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
      steps:
        - uses: actions/checkout@v3

        - name: Prepare repository
          run: git fetch --unshallow --tags

        - name: Use Node.js 16
          uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Create Release
          env:
            GITHUB_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
            APP_ID: ${{ secrets.APP_ID }}
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          run: |
            npm i
            npx auto shipit -vv
